[package]
name = "dicebotrs"
version = "0.1.0"
authors = ["peach <kittceon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
rand = "0.7.3"
regex = "1"
lazy_static = "1.4.0"
